version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
